{{ if $.Values.ingress.enable -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{ if and $.Values.ingress.tls.enable $.Values.ingress.tls.clusterIssuer -}}
    cert-manager.io/cluster-issuer: {{ $.Values.ingress.tls.clusterIssuer }}
    {{ end -}}
    kubernetes.io/ingress.class: {{ $.Values.ingress.class }}
  name: {{ $.Values.haproxy.name }}-ingress
  namespace: {{ $.Values.namespace }}
spec:
  rules:
  - host: {{ $.Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ $.Values.haproxy.name }}
            port: 
              number: 80
        pathType: Prefix
        path: /
  {{ if $.Values.ingress.tls.enable -}}
  tls:
  - hosts:
    - {{ $.Values.ingress.host }}
    secretName: jitsi-tls
  {{ end -}}
{{ end -}}
